spring:
  application:
    name: geolocation_attendance
  data:
    mongodb:
      uri: "mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.5"
      database: "Geolocation-Based-Attendance"
  main:
    allow-bean-definition-overriding: true